name: build-fabulinus
on:
  push:
    branches: ["main"]

jobs:
  build-fabulinus:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"

      - name: Confirm git commit SHA output
        run: echo ${{ steps.vars.outputs.short_sha }}

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          target: prod
          push: true
          tags: |
            tytn/fabulinus:${{ steps.vars.outputs.short_sha }}-gpu
            tytn/fabulinus:latest-gpu
            tytn/fabulinus:latest
          cache-from: type=registry,ref=tytn/fabulinus:buildcache-gpu
          cache-to: type=registry,ref=tytn/fabulinus:buildcache-gpu,mode=max

      - name: build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.cpu
          target: prod
          push: true
          tags: |
            tytn/fabulinus:${{ steps.vars.outputs.short_sha }}-cpu
            tytn/fabulinus:latest-cpu
          cache-from: type=registry,ref=tytn/fabulinus:buildcache-cpu
          cache-to: type=registry,ref=tytn/fabulinus:buildcache-cpu,mode=max
